# Generated by Django 3.2.3 on 2021-05-29 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0002_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='url',
            new_name='account_url',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='url',
            new_name='project_url',
        ),
    ]
