# Generated by Django 3.2.3 on 2021-05-29 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0003_auto_20210529_1024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-pk']},
        ),
    ]
