# Generated by Django 3.2.3 on 2021-05-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0005_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=40),
        ),
    ]
